#!/usr/bin/env node
/**
 * sync-env.js
 * Reads the root .env file and writes all VITE_* variables into frontend/.env.
 * Run this script before starting the Vite dev server so the frontend always
 * gets its variables from the single source-of-truth root .env.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const rootEnv = join(rootDir, ".env");
const frontendEnv = join(rootDir, "frontend", ".env");

if (!existsSync(rootEnv)) {
  console.error("sync-env: root .env not found, skipping.");
  process.exit(0);
}

const lines = readFileSync(rootEnv, "utf8").split(/\r?\n/);

// Keep only VITE_* variable lines (skip blanks and comments)
const viteLines = lines.filter((line) => /^VITE_[A-Z0-9_]+=/.test(line.trim()));

const output =
  "# Auto-generated by scripts/sync-env.js — edit root .env instead\n" +
  viteLines.join("\n") +
  "\n";

writeFileSync(frontendEnv, output, "utf8");
console.log(`sync-env: wrote ${frontendEnv}`);
